name: Build minicap

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  check:
    name: Check if new commit
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    steps:
      # checkout
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: DeviceFarmer/minicap
          submodules: true
          path: DeviceFarmer_minicap

      - name: Get Release
        uses: ctrlaltdev/get-releases-action@v1.1.0
        id: get_latest
        with:
          repo: QZLin/minicap
          limit: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: test
        run: |
          echo v:$env:last_release
          echo v:$env:this_repo
          # echo v:$env:a
          # ls Env:
        env:
          last_release: ${{ steps.get_latest.outputs.releases }}
          this_repo: ${{ env.GITHUB_REPOSITORY }}
          # a: hiworld

      - name: check
        id: checker
        run: . ./check_if_new.ps1
        env:
          last_release: ${{ steps.get_latest.outputs.releases }}

      # - name: test
      #   run: echo v:$Env:a
      #   env:
      #     a: ${{ env.new_commit }}

      - name: Cancel this build
        uses: andymckay/cancel-action@0.2
        if: ${{ ! env.new_commit }}

      - name: Set outputs
        id: out
        run: |
          echo "::set-output name=current_commit::$($Env:current_commit)"
          echo "::set-output name=current_commit_msg::$($Env:current_commit_msg)"

  build:
    needs: check
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    steps:
      # - name: Android NDK toolchain Setup
      #   uses: nttld/setup-ndk@v1.0.6
      #   with:
      #     ndk-version: r21e

      # - uses: actions/checkout@v2
      #   with:
      #     repository: DeviceFarmer/minicap
      #     submodules: true
      #     path: DeviceFarmer_minicap

      # - run: ls

      # - name: Build
      #   run: |
      #     Push-Location DeviceFarmer_minicap
      #     ndk-build
      #     ls
      #     ls libs
      #     Write-Output Build finished!
      #     Pop-Location
      - name: Create fake output files for actions debug
        run: |
          mkdir DeviceFarmer_minicap
          mkdir DeviceFarmer_minicap/libs
          New-Item .\DeviceFarmer_minicap\libs\test.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: libs
          path: DeviceFarmer_minicap/libs
          retention-days: 1
      - name: Compress output
        run: Compress-Archive -Path DeviceFarmer_minicap/libs -DestinationPath libs.zip

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ needs.check.out.current_commit_msg }}
          tag: ${{ needs.check.out.current_commit }}
          body: This is an auto release by github actions
          files: libs.zip
