name: Build minicap

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    steps:
      - name: Android NDK toolchain Setup
        uses: nttld/setup-ndk@v1.0.6
        with:
          ndk-version: r21e

      - uses: actions/checkout@v2
        with:
          repository: DeviceFarmer/minicap
          submodules: true

      - run: ls

      - name: Build
        run: |
          ndk-build
          ls
          ls libs
          Write-Output Build finish!
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: libs
          path: libs
          retention-days: 30
